version: '3.8'

services:

  hohoja_backend:
      image:  registry.gitlab.com/nccu_se_2024/tzuchiandbrothers/deployteam/backend
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: hohoja_backend_container
      env_file:
        - .env
      networks:
        - hohoja_network

  hohoja_frontend:
      image: registry.gitlab.com/nccu_se_2024/tzuchiandbrothers/deployteam/frontend:latest
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: hohoja_frontend_container
      env_file:
        - .env
      networks:
        - hohoja_network

  # redis:
  #   image: redis
  #   container_name: redis_container
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - hohoja_network
  #   depends_on:
  #     - hohoja_backend
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hohoja_network
    depends_on:
      - hohoja_backend


networks:
  hohoja_network:   
