name: Deployment

# 一次只能有一個 workflow 執行
concurrency: production

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-push-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          docker login registry.gitlab.com -u${{ secrets.GITLAB_DEPLOY_USER }} --password-stdin <<<${{ secrets.GITLAB_DEPLOY_TOKEN }}
          docker-compose build
          docker-compose push

  create-env-files-on-ec2:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh
        uses: appleboy/ssh-action@v1.0.3
        env:
          NGINX_CONF: ${{ secrets.NGINX_CONF }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          envs: NGINX_CONF
          script: |
            cd ${{ secrets.EC2_DEPLOY_PATH }}
            echo "${{ secrets.DOTENV }}" > .env
            echo "$NGINX_CONF" > nginx.conf

  copy-docker-compose-file-to-ec2:
    runs-on: ubuntu-latest
    needs: create-env-files-on-ec2
    steps:
    - uses: actions/checkout@v2
    - name: Copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "docker-compose.yml"
        target: ${{ secrets.EC2_DEPLOY_PATH }}

  restart-server:
    runs-on: ubuntu-latest
    needs: [copy-docker-compose-file-to-ec2, create-env-files-on-ec2, build-push-image]
    steps:
    - name: Restart server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.EC2_DEPLOY_PATH }}
          bash restart.sh