name: Test

on:
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main
      - develop
  workflow_call: # 可以被其他 workflow 呼叫

defaults:
  run:
    working-directory: ./backend
    
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Run testing db using docker
        run: docker run -d -p 3307:3306 nccusoftware/testing-db
      - name: Wait for db to start
        run: sleep 10
      - name: Import environment variables from secret file
        shell: bash
        run:  echo "${{ secrets.TEST_DOT_ENV }}" > .env.test
      - name: Run unit tests
        run: npm test
      - name: Send Notification to Discord
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitHub Bot"
          message: |
            **[Test]** Tests completed. The **「${{ github.event_name }}」** event triggered by **「${{ github.actor }}」** on **${{ github.ref }}** succeeded.
      - name: Send Notification to Discord
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitHub Bot"
          message: |
            **[Test]** Tests completed,but failed. The **「${{ github.event_name }}」** event triggered by **「${{ github.actor }}」** on **${{ github.ref }}** failed.
    