name: Test build

on:
  push:
    branches:
      - fix/undefeind_next_public_domain_url

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          docker login registry.gitlab.com -u${{ secrets.GITLAB_DEPLOY_USER }} --password-stdin <<<${{ secrets.GITLAB_DEPLOY_TOKEN }}
          docker-compose build --no-cache
